bootstrap/125318 - fix gcc/tree-vect-stmts.cc uninit error
Without the change gcc fails to build on master in
--enable-checking=release mode as:

    gcc/tree-vect-stmts.cc:10408:47: error: ‘stride_step’
      may be used uninitialized [-Werror=maybe-uninitialized]

This happens due to a limit hit in uninit anaysis. To avoid intermittent
build failures dependent on code size let's unconditionally initialize
the stride_step.

	PR bootstrap/125318
	* tree-vect-stmts.cc (vectorizable_load): Explicitly
	initialize stride_step to work around
	-Werror=maybe-uninitialized build failure.