Pass pratt parsed token to expr parser functions to fix expr locus
The pratt parser skips the first token of an expression before
invoking the actual expression parsing function. This makes getting
the correct starting location of a pratt parsed expression hard. The
"correction" of the location by subtracting an integer is often wrong
(since there may be arbitrary whitespace or comments between
tokens). Fix this by passing the token to the expression parsing
functions (instead of just providing a pratt_parse boolean). Use this
token to set the start of the expression.

Before gccrs would generate the following error message:

return.rs:3:22: error: cannot ‘break’ outside of a loop
    3 |     let x = 5 - break return (16 + 2);
      |                      ^~~~~~~~~~~~~~~~~

Now we get:

return.rs:3:17: error: cannot ‘break’ outside of a loop
    3 |     let x = 5 - break return (16 + 2);
      |                 ^