Address 'gcc/rust/typecheck/rust-tyty.h' '-Werror=unused-parameter' diagnostics [#336]
    In file included from [...]/gcc/rust/typecheck/rust-hir-type-check.h:24,
                     from [...]/gcc/rust/resolve/rust-name-resolver.h:24,
                     from [...]/gcc/rust/resolve/rust-ast-resolve.h:22,
                     from [...]/gcc/rust/rust-session-manager.cc:36:
    [...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::USizeType::USizeType(Rust::HirId, std::set<unsigned int>)’:
    [...]/gcc/rust/typecheck/rust-tyty.h:972:41: error: unused parameter ‘refs’ [-Werror=unused-parameter]
      972 |   USizeType (HirId ref, std::set<HirId> refs = std::set<HirId> ())
          |                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    [...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::USizeType::USizeType(Rust::HirId, Rust::HirId, std::set<unsigned int>)’:
    [...]/gcc/rust/typecheck/rust-tyty.h:976:55: error: unused parameter ‘refs’ [-Werror=unused-parameter]
      976 |   USizeType (HirId ref, HirId ty_ref, std::set<HirId> refs = std::set<HirId> ())
          |                                       ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    [...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::ISizeType::ISizeType(Rust::HirId, std::set<unsigned int>)’:
    [...]/gcc/rust/typecheck/rust-tyty.h:994:41: error: unused parameter ‘refs’ [-Werror=unused-parameter]
      994 |   ISizeType (HirId ref, std::set<HirId> refs = std::set<HirId> ())
          |                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    [...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::ISizeType::ISizeType(Rust::HirId, Rust::HirId, std::set<unsigned int>)’:
    [...]/gcc/rust/typecheck/rust-tyty.h:998:55: error: unused parameter ‘refs’ [-Werror=unused-parameter]
      998 |   ISizeType (HirId ref, HirId ty_ref, std::set<HirId> refs = std::set<HirId> ())
          |                                       ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    [...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::CharType::CharType(Rust::HirId, std::set<unsigned int>)’:
    [...]/gcc/rust/typecheck/rust-tyty.h:1016:40: error: unused parameter ‘refs’ [-Werror=unused-parameter]
     1016 |   CharType (HirId ref, std::set<HirId> refs = std::set<HirId> ())
          |                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    [...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::CharType::CharType(Rust::HirId, Rust::HirId, std::set<unsigned int>)’:
    [...]/gcc/rust/typecheck/rust-tyty.h:1020:54: error: unused parameter ‘refs’ [-Werror=unused-parameter]
     1020 |   CharType (HirId ref, HirId ty_ref, std::set<HirId> refs = std::set<HirId> ())
          |                                      ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    [...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::ReferenceType::ReferenceType(Rust::HirId, Rust::TyTy::TyVar, std::set<unsigned int>)’:
    [...]/gcc/rust/typecheck/rust-tyty.h:1040:34: error: unused parameter ‘refs’ [-Werror=unused-parameter]
     1040 |                  std::set<HirId> refs = std::set<HirId> ())
          |                  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    [...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::ReferenceType::ReferenceType(Rust::HirId, Rust::HirId, Rust::TyTy::TyVar, std::set<unsigned int>)’:
    [...]/gcc/rust/typecheck/rust-tyty.h:1045:34: error: unused parameter ‘refs’ [-Werror=unused-parameter]
     1045 |                  std::set<HirId> refs = std::set<HirId> ())
          |                  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    [...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::StrType::StrType(Rust::HirId, std::set<unsigned int>)’:
    [...]/gcc/rust/typecheck/rust-tyty.h:1070:39: error: unused parameter ‘refs’ [-Werror=unused-parameter]
     1070 |   StrType (HirId ref, std::set<HirId> refs = std::set<HirId> ())
          |                       ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    [...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::StrType::StrType(Rust::HirId, Rust::HirId, std::set<unsigned int>)’:
    [...]/gcc/rust/typecheck/rust-tyty.h:1074:53: error: unused parameter ‘refs’ [-Werror=unused-parameter]
     1074 |   StrType (HirId ref, HirId ty_ref, std::set<HirId> refs = std::set<HirId> ())
          |                                     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~