Fix m68k bootstrap due to diagnostic
The m68k port stopped bootstrapping recently because of this error:

> In file included from ./tm.h:31,
>                  from ../../../gcc/gcc/target.h:52,
>                  from ../../../gcc/gcc/dwarf2cfi.cc:23:
> ../../../gcc/gcc/dwarf2cfi.cc: In function 'bool dwarf2out_do_cfi_asm()':
> ../../../gcc/gcc/config/m68k/m68k.h:780:22: error: use of logical '||' with constant operand '2' [-Werror=constant-logical-operand]
>   780 |         && ((GLOBAL) || (CODE)))                                           \
>       |             ~~~~~~~~~^~~~~~~~~
> ../../../gcc/gcc/dwarf2cfi.cc:3755:9: note: in expansion of macro 'ASM_PREFERRED_EH_DATA_FORMAT'
>  3755 |   enc = ASM_PREFERRED_EH_DATA_FORMAT (/*code=*/2,/*global=*/1);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../../gcc/gcc/config/m68k/m68k.h:780:22: note: use '|' for bitwise operation
> ../../../gcc/gcc/dwarf2cfi.cc:3755:9: note: in expansion of macro 'ASM_PREFERRED_EH_DATA_FORMAT'
>  3755 |   enc = ASM_PREFERRED_EH_DATA_FORMAT (/*code=*/2,/*global=*/1);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Note the "2" being passed down.  That's what triggers the warning.  The
semantic preserving change is to use !!CODE.  Given the port won't currently
bootstrap, I'm committing as-is.

gcc/

	* config/m68k/m68k.h (ASM_PREFERRED_EH_DATA_FORMAT): Avoid
	constant-logical diagnostic.