Fix '#include <algorithm>'
GCC doesn't like that:

    In file included from [...]
    ./mm_malloc.h:42:12: error: attempt to use poisoned "malloc"
         return malloc (__size);
            ^

See commit e7b3f654f2ab0400c95c0517387a9ad645a5c4cd, for example.