libgomp: Fix env.c compilation on Darwin
Darwin bootstrap is currently broken compiling libgomp/env.c:

libgomp/env.c: In function 'initialize_env':
libgomp/env.c:2476:7: error: use of logical '||' with constant operand '2097152' [-Werror=constant-logical-operand]
 2476 |       || GOMP_DEFAULT_STACKSIZE)
      |       ^~
libgomp/env.c:2476:7: note: use '|' for bitwise operation
 2476 |       || GOMP_DEFAULT_STACKSIZE)
      |       ^~

This is only seen on Darwin since this is the only target that defines a
non-zero GOMP_DEFAULT_STACKSIZE.

Bootstrapped without regressions on x86_64-apple-darwin25.5.0 and
x86_64-apple-darwin21.6.0.

2026-05-16  Rainer Orth  <ro@CeBiTec.Uni-Bielefeld.DE>

	libgomp:
	* env.c (initialize_env): Check GOMP_DEFAULT_STACKSIZE for
	non-zero.