libgomp: Don't use alloca directly
This patch

commit a36f0edbec6f2ef36792eda245fa7e512d032872
Author: Arsen Arsenović <aarsenovic@baylibre.com>
Date:   Thu Apr 23 10:47:38 2026 +0000

    libgomp: let plugins handle allocating the target variable table

broke Solaris bootstrap:

In file included from libgomp/oacc-parallel.c:30:
libgomp/oacc-parallel.c: In function ‘GOACC_parallel_keyed’:
libgomp/oacc-parallel.c:297:45: error: implicit declaration of function ‘alloca’ [-Wimplicit-function-declaration]
  297 |        : gomp_offload_session_new (acc_dev, alloca));
      |                                             ^~~~~~
libgomp/libgomp.h:1510:21: note: in definition of macro ‘gomp_offload_session_new’
 1510 |     void *session = alloc (devicep->session.size);      \
      |                     ^~~~~
libgomp/oacc-parallel.c:297:45: error: incompatible implicit declaration of built-in function ‘alloca’ [-Werror=builtin-declaration-mismatch]
libgomp/libgomp.h:1510:21: note: in definition of macro ‘gomp_offload_session_new’
 1510 |     void *session = alloc (devicep->session.size);      \
      |                     ^~~~~

and similarly in target.c.

alloca is declared in <alloca.h> on Solaris.  Therefore the code should
use gomp_alloca instead, which is just for such cases.

Bootstrapped without regressions on i386-pc-solaris2.11,
sparc-sun-solaris2.11, and x86_64-pc-linux-gnu.

2026-06-01  Rainer Orth  <ro@CeBiTec.Uni-Bielefeld.DE>

	libgomp:
	* oacc-parallel.c (GOACC_parallel_keyed): Use gomp_alloca instead
	of alloca.
	* target.c (GOMP_target): Likewise.
	(GOMP_target_ext): Likewise.