testsuite: i386: Fix gcc.dg/analyzer/null-deref-pr123981-1.c
The gcc.dg/analyzer/null-deref-pr123981-1.c test FAILs on 64-bit x86
targets with -m32:

FAIL: gcc.dg/analyzer/null-deref-pr123981-1.c (test for excess errors)

gcc.dg/analyzer/null-deref-pr123981-1.c:10:3: error: implicit declaration of function '_writegsbase_u64' [-Wimplicit-function-declaration]
gcc.dg/analyzer/null-deref-pr123981-1.c:10:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]

As always, restricting x86 tests by target triplet is wrong: instead of
target x86_64-*-* this needs to be x86 && lp64.

Tested on amd64-pc-solaris2.11, i386-pc-solaris2.11, and
x86_64-pc-linux-gnu.

2026-03-31  Rainer Orth  <ro@CeBiTec.Uni-Bielefeld.DE>

	gcc/testsuite:
	* gcc.dg/analyzer/null-deref-pr123981-1.c: Restrict to 64-bit x86.