libgrust: Vendor Rust dependencies: Fix configuration file
If I run 'cargo vendor', it tells me the configuration file is
'.cargo/config.toml', not '.cargo/config'.  And indeed, with
'rm -rf ~/.cargo', the build then fails:

    [...]
    cd [...]/gcc/../libgrust/libformat_parser && cargo build --offline  # FIXME: Not always release, right?
    error: no matching package named `libc` found
    location searched: registry `crates-io`
    required by package `libformat_parser v0.1.0 ([...]/libgrust/libformat_parser)`
    As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
    make[2]: *** [[...]/gcc/rust/Make-lang.in:426: rust/libformat_parser.a] Error 101
    [...]

	libgrust/
	* libformat_parser/.cargo/config: Rename to...
	* libformat_parser/.cargo/config.toml: ... this.