libphobos: Implement IeeeFlags on SPARC [PR123202]
The libphobos.phobos/std_math_hardware.d test FAILs on SPARC:

FAIL: libphobos.phobos/std_math_hardware.d (test for excess errors)
UNRESOLVED: libphobos.phobos/std_math_hardware.d compilation failed to produce executable

Excess errors:
libphobos.phobos/std_math_hardware.d:7: error: undefined identifier 'FloatingPointControl'

There's currently no support for IeeeFlags on SPARC.

One part of an implementation has already been committed to upstream phobos

commit aa963e98c55b36b5d608f9443d96c66b63d16d8f
Author: Rainer Orth <ro@CeBiTec.Uni-Bielefeld.DE>
Date:   Thu Feb 19 12:47:58 2026 +0100

    std/math/hardware.d: Partial IeeeFlags implementation on SPARC (#10958)

but the actual implementation is specific to a GDC-specific part of
hardware.d which isn't upstream yet.  This patch provides that part.

Tested on sparc-sun-solaris2.11 and sparc64-unknown-linux-gnu.

2025-12-19  Rainer Orth  <ro@CeBiTec.Uni-Bielefeld.DE>

	libphobos:
	PR d/123202
	* src/std/math/hardware.d (getIeeeFlags) [GNU && SPARC_Any]: Implement.
	(resetIeeeFlags) [GNU && SPARC_Any]: Likewise.
	(hasExceptionTraps) [SPARC_Any]: Return true.
	(getControlState) [GNU && SPARC_Any]: Implement.
	(setControlState) [GNU && SPARC_Any]: Likewise.