testsuite: Remove -O options from some mips.exp tests
Running mips.exp generated several errors like:

ERROR: gcc.target/mips/pr118608-1.c   -O0 : Unrecognised option: -O2 for " dg-options 2 "-mabi=64 -O2" "

mips.exp overrides dg-options with some logic to (try to) enable
the transitive closure of features that would be needed to make the
dg-options valid for the current test run, downgrading from run to
assemble to compile as neecessary.  In order to make sure that
every relevant option has been considered, this version of dg-options
errors out for things that it doesn't recognise.

-O options aren't in the list because mips.exp cycles through the usual
optimisation options.  Instead, dg-skips are used if the test doesn't
make sense for a particular -O* option.

Removing the -O options makes pr118608-2.c identical to pr118608-1.c
and pr118608-4.c identical to pr118608-3.c.

gcc/testsuite/
	* gcc.target/mips/pr118608-2.c: Delete.
	* gcc.target/mips/pr118608-4.c: Likewise.
	* gcc.target/mips/pr123833.c: Remove -O* option.
	* gcc.target/mips/pr118608-1.c: Likewise.
	* gcc.target/mips/pr118608-3.c: Likewise, and rename to pr118608-2.c.