AVR: target/125409 - Add fixed-point conversions to / from [u]int24_t.
The test cases ran into

    ld: undefined reference to `__fractunssapsi'
    ld: undefined reference to `__fractunspsisa'

etc. because the backend didn't implement these conversions.
The worker function that outputs fixed-point conversions inline,
avr_out_fract, is generic enough to handle 24-bit integral modes, so
adding PSImode to the mode iterators in avr-fixed.md fixes the issue.

	PR target/125409
gcc/
	* config/avr/avr-fixed.md (FIXED_A, FIXED_B): Add PSI to iterators.

gcc/testsuite/
	* gcc.target/avr/torture/pr125409.h: New file.
	* gcc.target/avr/torture/pr125409-fx24-ssk.c: New test.
	* gcc.target/avr/torture/pr125409-fx24-ssr.c: New test.
	* gcc.target/avr/torture/pr125409-fx24-suk.c: New test.
	* gcc.target/avr/torture/pr125409-fx24-sur.c: New test.
	* gcc.target/avr/torture/pr125409-fx24-usk.c: New test.
	* gcc.target/avr/torture/pr125409-fx24-usr.c: New test.
	* gcc.target/avr/torture/pr125409-fx24-uuk.c: New test.
	* gcc.target/avr/torture/pr125409-fx24-uur.c: New test.