testsuite: get a predictable ordered array for comparison
Without this patch, errors like below can be seen in g++.log:

Traceback (most recent call last):
  File "/build/gcc_src/gcc/testsuite/g++.dg/modules/test-p1689.py", line 220, in <module>
    is_ok = validate_p1689(actual, expect)
...
  File "/build/gcc_src/gcc/testsuite/g++.dg/modules/test-p1689.py", line 149, in compare_json
    actual = set(actual)
TypeError: unhashable type: 'dict'

To avoid hashing dicts, transform the elements to string representation
prior to sorting the array and then transform back to objects after.

gcc/testsuite/ChangeLog:

	* g++.dg/modules/test-p1689.py: Make arrays have predictable
	order.

Signed-off-by: Torbjörn SVENSSON <torbjorn.svensson@foss.st.com>